### ISSUE TITLE
Plasma Stick - Weather Example Fails  - OSError: [Errno 12] ENOMEM

### ISSUE THREAD

**Issue by digitalurban** [pimoroni/pimoroni-pico#634]
Afternoon  - 

The example for the plasma stick - weather.py connects once and then fails:

Connection successful!
Requesting URL: https://api.open-meteo.com/v1/forecast?latitude=52.6216&longitude=0.4968&current_weather=true&timezone=auto
Data obtained!
Temperature = 6.0°C
Conditions = cloudy
Last Open-Meteo update: 2023-01-15, 13:00
    
Requesting URL: https://api.open-meteo.com/v1/forecast?latitude=52.6216&longitude=0.4968&current_weather=true&timezone=auto
Traceback (most recent call last):
  File "<stdin>", line 248, in <lambda>
  File "<stdin>", line 91, in get_data
  File "urequests.py", line 180, in get
  File "urequests.py", line 93, in request
OSError: [Errno 12] ENOMEM

Thought i would highlight this in case others are having the sample issue,

Andy

**Comment by digitalurban** [comment]
Edit - noted this was fixed with a recent update...
