### ISSUE TITLE
Galactic Unicorn WiFi Paint Server Error

### ISSUE THREAD

**Issue by fallenartist** [pimoroni/pimoroni-pico#688]
Hello,
I'm getting the following error when running Galactic Paint example in Shell:

```
Start painting at: http://192.168.1.105
Traceback (most recent call last):
  File "/lib/microdot_asyncio.py", line 368, in dispatch_request
  File "/lib/microdot_asyncio.py", line 431, in _invoke_handler
  File "<stdin>", line 27, in route_index
  File "/lib/microdot.py", line 664, in send_file
OSError: [Errno 2] ENOENT
```

plus `Internal server error` in the browser.

I've installed latest libraries per the instructions. Not sure what else can be done? Thanks.

**Comment by helgibbons** [comment]
Ooh, I ran into this one yesterday!

Check your `galactic_paint.py` is in the root directory of the Pico and `index.html` and the `static` dir should be in a directory called `galactic_paint`.

![image](https://user-images.githubusercontent.com/50950368/221187025-5deecf2c-9d0f-4cec-84f0-d00369692b38.png)
